const data_pincodeRedemptions = {
  types: [
    {
      channel: "SMS",
      msisdn: "•••••••6190",
      pincode: "5•••••••9",
      middlewareStatus: "Successful",
      referenceID: "yhZazo8jcKiDu",
      transID: "6084408cb55e3a664a50e6f",
      gatewayStatus: "Failed",
      firstName: "Tyronne Jeff",
      lastName: "Galvez",
      age: 35,
      location: "Northern Mindanao",
      date: "09-Nov-21 05:18:02 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••3726",
      pincode: "R•••••••3",
      middlewareStatus: "Successful",
      referenceID: "ThZwz3UjcKiDu",
      transID: "6084408cb55e3a664a50g54",
      gatewayStatus: "Failed",
      firstName: "John Paul",
      lastName: "Quijano",
      age: 23,
      location: "Southern Luzon",
      date: "09-Nov-21 06:21:05 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••9288",
      pincode: "x•••••••E",
      middlewareStatus: "Failed",
      referenceID: "zhBa2o8jcGiDu",
      transID: "6084408cb55e3a664a502Ef",
      gatewayStatus: "Failed",
      firstName: "Edrill Rose",
      lastName: "Kalimdogan",
      age: 28,
      location: "NCR",
      date: "09-Nov-21 07:34:56 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••1009",
      pincode: "9•••••••1",
      middlewareStatus: "Successful",
      referenceID: "8hBao8jc0iVu",
      transID: "6084408cb55e3a664a524fs",
      gatewayStatus: "Successful",
      firstName: "Aprille",
      lastName: "Quiverdo",
      age: 19,
      location: "NCR",
      date: "09-Nov-21 08:34:01 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••7865",
      pincode: "Q•••••••r",
      middlewareStatus: "Failed",
      referenceID: "1hBa2o8jcWi9u",
      transID: "6084408cb55e3a664a5rt67",
      gatewayStatus: "Failed",
      firstName: "Rochelle May",
      lastName: "Panaligan",
      age: 25,
      location: "NCR",
      date: "09-Nov-21 09:11:29 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••0119",
      pincode: "B•••••••b",
      middlewareStatus: "Successful",
      referenceID: "yhZazo8jcQrdf",
      transID: "6084408cb55e3a664a5qeds",
      gatewayStatus: "Successful",
      firstName: "Francis Liam",
      lastName: "Reyes",
      age: 25,
      location: "Western Visayas",
      date: "09-Nov-21 10:34:00 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••8221",
      pincode: "1•••••••f",
      middlewareStatus: "Successful",
      referenceID: "ThZwz3Ujcbarj",
      transID: "6084408cb55e3a664a5o09g",
      gatewayStatus: "Successful",
      firstName: "Sir Alfred",
      lastName: "Dy",
      age: 59,
      location: "NCR",
      date: "09-Nov-21 11:19:46 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••5544",
      pincode: "D•••••••j",
      middlewareStatus: "Successful",
      referenceID: "1hBa2o8jcWw3rh",
      transID: "6084408cb55e3a664a5624r",
      gatewayStatus: "Successful",
      firstName: "Machintal",
      lastName: "Meer",
      age: 64,
      location: "NCR",
      date: "09-Nov-21 12:00:23 AM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••6191",
      pincode: "W•••••••0",
      middlewareStatus: "Successful",
      referenceID: "yhZazo8jcKiDy",
      transID: "6084408cb55e3a664a50e6h",
      gatewayStatus: "Failed",
      firstName: "Tyronne Jeff",
      lastName: "Galvez",
      age: 35,
      location: "Northern Mindanao",
      date: "09-Nov-21 05:18:02 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••3727",
      pincode: "H•••••••l",
      middlewareStatus: "Successful",
      referenceID: "ThZwz3UjcKiDy",
      transID: "6084408cb55e3a664a50g58",
      gatewayStatus: "Failed",
      firstName: "John Paul",
      lastName: "Quijano",
      age: 23,
      location: "Southern Luzon",
      date: "09-Nov-21 06:21:05 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••9289",
      pincode: "1•••••••k",
      middlewareStatus: "Failed",
      referenceID: "zhBa2o8jcGiDb",
      transID: "6084408cb55e3a664a502Ei",
      gatewayStatus: "Failed",
      firstName: "Edrill Rose",
      lastName: "Kalimdogan",
      age: 28,
      location: "NCR",
      date: "09-Nov-21 07:34:56 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••1029",
      pincode: "C•••••••5",
      middlewareStatus: "Successful",
      referenceID: "8hBao8jc0iVt",
      transID: "6084408cb55e3a664a524ft",
      gatewayStatus: "Successful",
      firstName: "Aprille",
      lastName: "Quiverdo",
      age: 19,
      location: "NCR",
      date: "09-Nov-21 08:34:01 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••7862",
      pincode: "H•••••••w",
      middlewareStatus: "Failed",
      referenceID: "1hBa2o8jcWi9a",
      transID: "6084408cb55e3a664a5rt68",
      gatewayStatus: "Failed",
      firstName: "Rochelle May",
      lastName: "Panaligan",
      age: 25,
      location: "NCR",
      date: "09-Nov-21 09:11:29 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••0219",
      pincode: "Q•••••••y",
      middlewareStatus: "Successful",
      referenceID: "yhZazo8jcQrdl",
      transID: "6084408cb55e3a664a5qed7",
      gatewayStatus: "Successful",
      firstName: "Francis Liam",
      lastName: "Reyes",
      age: 25,
      location: "Western Visayas",
      date: "09-Nov-21 10:34:00 PM",
    },
    {
      channel: "SMS",
      msisdn: "•••••••8223",
      pincode: "9•••••••o",
      middlewareStatus: "Successful",
      referenceID: "ThZwz3Ujcbarq",
      transID: "6084408cb55e3a664a5o09q",
      gatewayStatus: "Successful",
      firstName: "Sir Alfred",
      lastName: "Dy",
      age: 59,
      location: "NCR",
      date: "09-Nov-21 11:19:46 PM",
    },
    {
      channel: "Chatbot",
      msisdn: "•••••••5540",
      pincode: "M•••••••x",
      middlewareStatus: "Successful",
      referenceID: "1hBa2o8jcWw3ro",
      transID: "6084408cb55e3a664a5624n",
      gatewayStatus: "Successful",
      firstName: "Machintal",
      lastName: "Meer",
      age: 64,
      location: "NCR",
      date: "09-Nov-21 12:00:23 AM",
    },
  ],
}

export default data_pincodeRedemptions
